# site properties and page defaults
title: QUANTA
subtitle: Quantum Understanding, Algorithms, Networks, Technologies, and Applications Research Group
description: An easy-to-use, flexible website template for labs, with automatic citations, GitHub tag imports, pre-built components, and more.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: crbellor@unal.edu.co
  orcid: 0000-0002-3991-4008
  google-scholar: https://scholar.google.com/citations?user=2-v96LsAAAAJ&hl=es
  github: https://github.com/QUANTA-Research-Group
  twitter: https://x.com/QuantumColombia
  youtube: https://www.youtube.com/@Quantum_Colombia

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
